apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-express
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: hello-express
    spec:
      containers:
      - name: hello-express
        image: hello-express:latest
        imagePullPolicy: IfNotPresent
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: express-configmap
              key: PORT
        - name: stringval
          valueFrom:
            configMapKeyRef:
              name: express-configmap
              key: stringval
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: express-secrets
              key: API_TOKEN
