apiVersion: v1
kind: Service
metadata:
  name: hello-express
  labels:
    application: hello-express
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    application: hello-express
  type: LoadBalancer
